stages:
  - migrating

migrating-database:
  stage: migrating
  tags:
    - be-duitku
  only:
    - main
  script:
    - echo "running migration"
    - cp /home/duitku-env/.env-duitku-migration .env
    - ./migrate-fresh.sh

