stages:
  - build

build-image:
  stage: build
  tags:
    - be-duitku
  only:
    - main
  script:
    - echo "running build stage"
    - docker image prune -f
    - cp /home/duitku-env/.env-duitku-backend .env
    - docker compose up -d --build

