services:
  server:
    build:
      context: .
    volumes:
      - ./.env:/app/.env
    ports:
      - 8899:8899
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - NGINX_PORT=${NGINX_PORT}
      - SERVER_PORT=${GOLANG_PORT}
      - APP_ENV=${APP_ENV}
