package Dto

// ----- client request --- //
type PurchasedItem struct {
	ID           string `json:"id" binding:"required"`
	QuantitySold int    `json:"quantity_sold" binding:"required"`
	TotalPrice   int    `json:"total_price" binding:"required"`
}

type InvoiceRequestClient struct {
	InvoiceCustomer string          `json:"invoice_customer" binding:"required"`
	PaymentMethodID string          `json:"payment_method_id" binding:"required"`
	Purchaseds      []PurchasedItem `json:"purchaseds" binding:"required,dive"`
}

type InvoiceRequestDTO struct {
	ID              string `json:"id"` // generated by gorm
	InvoiceNumber   string `json:"invoice_number" binding:"required"`
	InvoiceCustomer string `json:"invoice_customer" binding:"required"`
	InvoiceDate     string `json:"invoice_date"`
	TotalAmount     int    `json:"total_amount"`
	MoneyReceived   int    `json:"money_received"`
	StatusInvoice   string `json:"status_invoice"`
	CompanyID       string `json:"company_id" binding:"required"`
	PaymentMethodId string `json:"payment_method_id"`
}

type InvoiceMaterialRequestDTO struct {
	InvoiceID         string `json:"invoice_id" binding:"required"`
	MaterialProductID string `json:"material_product_id" binding:"required"`
	QuantitySold      int    `json:"quantity_sold" binding:"required"`
	CompanyID         string `json:"company_id" binding:"required"`
}

type InvoiceSaleableRequestDTO struct {
	InvoiceID         string `json:"invoice_id" binding:"required"`
	SaleableProductID string `json:"saleable_product_id" binding:"required"`
	QuantitySold      int    `json:"quantity_sold" binding:"required"`
	CompanyID         string `json:"company_id" binding:"required"`
}

type InvoiceStatusRequestDTO struct {
	StatusInvoice string `json:"status_invoice" binding:"required"`
}

type InvoiceMoneyReceivedRequestDTO struct {
	MoneyReceived float64 `json:"money_received" binding:"required"`
}

type InvoiceUpdateRequestDTO struct {
	InvoiceNumber   string `json:"invoice_number"`
	InvoiceCustomer string `json:"invoice_customer"`
	InvoiceDate     string `json:"invoice_date"`
	TotalAmount     int    `json:"total_amount"`
	MoneyReceived   int    `json:"money_received"`
	StatusInvoice   string `json:"status_invoice"`
	PaymentMethodId string `json:"payment_method_id"`
}

type UpdateInvoiceDetailRequestDTO struct {
	Purchaseds []PurchasedItem `json:"purchaseds" binding:"required,dive"`
}
