// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package Di

import (
	"2024_akutansi_project/Controllers"
	"2024_akutansi_project/Middleware"
	"2024_akutansi_project/Repositories"
	"2024_akutansi_project/Services"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func DIAuth(db *gorm.DB) *Controllers.AuthController {
	authRepository := Repositories.AuthRepositoryProvider(db)
	jwtService := Services.JwtServiceProvider()
	authService := Services.AuthServiceProvider(authRepository, jwtService)
	authController := Controllers.AuthControllerProvider(authService)
	return authController
}

func DICommonMiddleware(db *gorm.DB) *Middleware.CommondMiddleware {
	jwtService := Services.JwtServiceProvider()
	authRepository := Repositories.AuthRepositoryProvider(db)
	commondMiddleware := Middleware.CommonMiddlewareProvider(jwtService, authRepository)
	return commondMiddleware
}

func DICompany(db *gorm.DB) *Controllers.CompanyController {
	companyRepository := Repositories.CompanyRepositoryProvider(db)
	userCompanyRepository := Repositories.UserCompanyRepositoryProvider(db)
	companyService := Services.CompanyServiceProvider(companyRepository, userCompanyRepository)
	companyController := Controllers.CompanyControllerProvider(companyService)
	return companyController
}
