// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package Di

import (
	"2024_akutansi_project/Connector"
	"2024_akutansi_project/Controllers"
	"2024_akutansi_project/Middleware"
	"2024_akutansi_project/Repositories"
	"2024_akutansi_project/Services"
	"firebase.google.com/go/messaging"
	"github.com/minio/minio-go/v7"
	"github.com/redis/go-redis/v9"
	"go.mongodb.org/mongo-driver/mongo"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func DIAuth(db *gorm.DB, redis2 *redis.Client) *Controllers.AuthController {
	userRepository := Repositories.UserRepositoryProvider(db)
	jwtService := Services.JwtServiceProvider()
	companyRepository := Repositories.CompanyRepositoryProvider(db)
	subUserRepository := Repositories.SubUserRepositoryProvider(db)
	accountRepository := Repositories.AccountProvider(db)
	authService := Services.AuthServiceProvider(userRepository, jwtService, companyRepository, subUserRepository, redis2, accountRepository)
	authController := Controllers.AuthControllerProvider(authService)
	return authController
}

func DICommonMiddleware(db *gorm.DB, redis2 *redis.Client) *Middleware.CommondMiddleware {
	jwtService := Services.JwtServiceProvider()
	commondMiddleware := Middleware.CommonMiddlewareProvider(jwtService, redis2)
	return commondMiddleware
}

func DIInvoice(db *gorm.DB) *Controllers.InvoiceController {
	invoiceRepository := Repositories.InvoiceRepositoryProvider(db)
	invoiceItemRepository := Repositories.InvoiceItemRepositoryProvider(db)
	sellableProductRepository := Repositories.SellableProductRepositoryProvider(db)
	receiptRepository := Repositories.ReceiptRepositoryProvider(db)
	materialProductRepository := Repositories.MaterialProductRepositoryProvider(db)
	sellableStockRepository := Repositories.SellableStockRepositoryProvider(db)
	materialStockRepository := Repositories.MaterialStockRepositoryProvider(db)
	journalEntriesRepository := Repositories.JournalEntriesProvider(db)
	accountRepository := Repositories.AccountProvider(db)
	transactionRepository := Repositories.TransactionRepositoryProvider(db)
	purchaseRepository := Repositories.PurchaseRepositoryProvider(db)
	journalEntriesService := Services.JournalEntriesProvider(journalEntriesRepository, accountRepository, transactionRepository, purchaseRepository)
	invoiceService := Services.InvoiceServiceProvider(invoiceRepository, invoiceItemRepository, sellableProductRepository, receiptRepository, materialProductRepository, sellableStockRepository, materialStockRepository, journalEntriesRepository, accountRepository, journalEntriesService, db)
	invoiceController := Controllers.InvoiceControllerProvider(invoiceService)
	return invoiceController
}

func DICategory(db *gorm.DB) *Controllers.CategoryController {
	categoryRepository := Repositories.CategoryRepositoryProvider(db)
	categoryService := Services.CategoryServiceProvider(categoryRepository)
	categoryController := Controllers.CategoryControllerProvider(categoryService)
	return categoryController
}

func DIProfile(db *gorm.DB, mongo2 *mongo.Client) *Controllers.ProfileController {
	profileRepository := Repositories.ProfileRepositoryProvider(mongo2)
	shopeeConnector := Connector.ShopeeConnectorProvider()
	profileService := Services.ProfileServiceProvider(profileRepository, shopeeConnector)
	profileController := Controllers.ProfileControllerProvider(profileService)
	return profileController
}

func DIWaitingList(db *gorm.DB) *Controllers.WaitingListController {
	waitingListRepository := Repositories.WaitingListRepositoryProvider(db)
	waitingListService := Services.WaitingListServiceProvider(waitingListRepository)
	waitingListController := Controllers.WaitingListControllerProvider(waitingListService)
	return waitingListController
}

func DIUnit(db *gorm.DB) *Controllers.UnitController {
	unitRepository := Repositories.UnitProvider(db)
	unitService := Services.UnitProvider(unitRepository)
	unitController := Controllers.UnitProvider(unitService)
	return unitController
}

func DIWorker(db *gorm.DB, mongo2 *mongo.Client, messaging2 *messaging.Client) *Services.WorkerService {
	deviceTokenRepository := Repositories.DeviceTokenRepositoryProvider(mongo2)
	notificationRepository := Repositories.NotificationRepositoryProvider(db)
	materialStockRepository := Repositories.MaterialStockRepositoryProvider(db)
	sellableProductRepository := Repositories.SellableProductRepositoryProvider(db)
	sellableStockRepository := Repositories.SellableStockRepositoryProvider(db)
	workerService := Services.WorkerServiceProvider(deviceTokenRepository, messaging2, notificationRepository, materialStockRepository, sellableProductRepository, sellableStockRepository)
	return workerService
}

func DITax(db *gorm.DB) *Controllers.TaxController {
	taxRepository := Repositories.TaxRepositoryProvider(db)
	taxService := Services.TaxServiceProvider(taxRepository)
	taxController := Controllers.TaxControllerProvider(taxService)
	return taxController
}

func DISubUser(db *gorm.DB) *Controllers.SubUserController {
	subUserRepository := Repositories.SubUserRepositoryProvider(db)
	subUserService := Services.SubUserProvider(subUserRepository)
	subUserController := Controllers.SubUserProvider(subUserService)
	return subUserController
}

func DIAccount(db *gorm.DB) *Controllers.AccountController {
	accountRepository := Repositories.AccountProvider(db)
	accountService := Services.AccountProvider(accountRepository)
	accountController := Controllers.AccountProvider(accountService)
	return accountController
}

func DISellableProduct(db *gorm.DB, minio2 *minio.Client) *Controllers.SellableProductController {
	sellableProductRepository := Repositories.SellableProductRepositoryProvider(db)
	promoItemRepository := Repositories.PromoItemRepositoryProvider(db)
	receiptRepository := Repositories.ReceiptRepositoryProvider(db)
	sellableStockRepository := Repositories.SellableStockRepositoryProvider(db)
	storageService := Services.StorageServiceProvider(minio2)
	promoRepository := Repositories.PromoRepositoryProvider(db)
	sellableProductService := Services.SellableProductServiceProvider(sellableProductRepository, promoItemRepository, receiptRepository, sellableStockRepository, db, storageService, promoRepository)
	sellableProductController := Controllers.SellableProductControllerProvider(sellableProductService, storageService)
	return sellableProductController
}

func DIMaterialProduct(db *gorm.DB) *Controllers.MaterialProductController {
	materialProductRepository := Repositories.MaterialProductRepositoryProvider(db)
	materialConversionRepository := Repositories.MaterialConversionRepositoryProvider(db)
	materialProductService := Services.MaterialProductServiceProvider(materialProductRepository, materialConversionRepository)
	materialProductController := Controllers.MaterialProductControllerProvider(materialProductService)
	return materialProductController
}

func DIStockOpname(db *gorm.DB) *Controllers.StockOpnameController {
	stockOpnameRepository := Repositories.StockOpnameRepositoryProvider(db)
	sellableStockRepository := Repositories.SellableStockRepositoryProvider(db)
	materialStockRepository := Repositories.MaterialStockRepositoryProvider(db)
	stockOpnameService := Services.StockOpnameServiceProvider(stockOpnameRepository, sellableStockRepository, materialStockRepository, db)
	stockOpnameController := Controllers.StockOpnameControllerProvider(stockOpnameService)
	return stockOpnameController
}

func DITransaction(db *gorm.DB) *Controllers.TransactionController {
	transactionRepository := Repositories.TransactionRepositoryProvider(db)
	transactionService := Services.TransactionServiceProvider(transactionRepository)
	transactionController := Controllers.TransactionControllerProvider(transactionService)
	return transactionController
}

func DIJournalEntries(db *gorm.DB) *Controllers.JournalEntriesController {
	journalEntriesRepository := Repositories.JournalEntriesProvider(db)
	accountRepository := Repositories.AccountProvider(db)
	transactionRepository := Repositories.TransactionRepositoryProvider(db)
	purchaseRepository := Repositories.PurchaseRepositoryProvider(db)
	journalEntriesService := Services.JournalEntriesProvider(journalEntriesRepository, accountRepository, transactionRepository, purchaseRepository)
	journalEntriesController := Controllers.JournalEntriesProvider(journalEntriesService)
	return journalEntriesController
}

func DIStorage(minio2 *minio.Client) *Controllers.StorageController {
	storageService := Services.StorageServiceProvider(minio2)
	storageController := Controllers.StorageControllerProvider(storageService)
	return storageController
}

func DiPurchase(db *gorm.DB) *Controllers.PurchaseController {
	sellableProductRepository := Repositories.SellableProductRepositoryProvider(db)
	materialProductRepository := Repositories.MaterialProductRepositoryProvider(db)
	materialStockRepository := Repositories.MaterialStockRepositoryProvider(db)
	sellableStockRepository := Repositories.SellableStockRepositoryProvider(db)
	purchaseSellableProductRepository := Repositories.PurchaseSellableProductRepositoryProvider(db)
	purchaseMaterialProductRepository := Repositories.PurchaseMaterialProductRepositoryProvider(db)
	purchaseRepository := Repositories.PurchaseRepositoryProvider(db)
	purchaseService := Services.PurchaseServiceProvider(sellableProductRepository, materialProductRepository, materialStockRepository, sellableStockRepository, purchaseSellableProductRepository, purchaseMaterialProductRepository, purchaseRepository)
	purchaseController := Controllers.PurchaseControllerProvider(purchaseService)
	return purchaseController
}
